dist: trusty
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-blog
  - secure: MFm3XV4tU4mkT7r091YNtSrnrjuPYVyoUdhpWJZiIO8sNx+Lz2HAcKqGrZf7jbJicqKbWmUWtp3RJq0oNbhhzcF9rQASRb7l65rBOnMIcVgeoLAKoNw7CP6lsaU69qQMhgIIhi/kP4P9SdSNEfUyIwJyRaihDta9xq3dCLz6Jyvf7oTW9q/6j2E/u+WVt7sQymhdryXJAlCINMunkYwLlK7cAS+6FuhiMlmG5XWV9C2/fB/PLRmpIvuTw9G9V9Euh97i9qokBQnWNJ84WWmIgLNVbECJof1UdnJ9Zw3seRimoKuampfDyd7BGbRXo5h4onlbxNypSB4LJaOMld0JUCD01tJXAv0aIfzWma6p7jU9mrdxO8m0TtuquJtZzn0yzJv4FQaHSN775BLy1T/v5ZHFJRGEbsnmquCBt7ELtM5Fjuk78gusPVTN0zYGdNN0fv/FUSqx6B4ayhGCJULo/aSzwtCH4GUyl5mY7CRwROU6RiKqaJpAJMLXJRLqMeok8n3085XB3GQBOXQv5Jr9N6Zal7TM8s2YfyYKIIV9P5bVJMbDPjClD+cTC7GEelBBCCYCX4eR2A+8nWUSBLoPCBFFNPqsScqgJzaV+1Sg5rkh4P+DaFv/pYK1zOnlr3Rfuiyp7rIWkn8dkb/St4LazmGNGY4Ci/cK8NfZrcr6rNA=
  - secure: gsEkrG3Pc4iqHIE34U2Qp+HvXfZg1Rr38Khxh2EXilggN/bg6kejPbfKMQ6h25iSc9H+KOCNSZ9+0hn6+SUSiaMh571ev6VCB0IbKhH48zNAOV/4sKZFZnsqXdH6Il2EJu7Ws14vmAEpwzHcQw68ibtAL3h976qjLHGu1WwBw535qoviG1FiVNaTWcRULAY08ksycfNA2Y1/MgxS5VptPNWisub1YxXDstcLDnJKHfE42ehAuvTpkViIi6Dh8VTaboyA06pkSN6/7RzyEFBVkVzb4/XG7LpYlAMhBuUUfC+sWiW02HriHsLy2R4QjfWJR75nlh63POhMpBzMvpQ5KKppAG8BFlGgs4i5O12kqJuIFm0yvYkNx8Tt1LOU+uYgxaq80WhB56DkDnkgEX4B5Kvloe948aPW1KFfq+oN40c89GcdrDrSdXvsEc5g/g3mhjBPFoFt7wWh7pu6xvnYdRWR40TcmeDfqLZNFiA4NGj1KMcy6sxiz27ZWkaN0S3+58hj4CyZzEg5ISiVexieuuYQtCBHUBTI0NOCbTeaXnqxyZKsDakOI2i5kulb4wL7UI2wIqJWxcAwPF+2OQov65eyBeJF9pTLC3Ptfm9I4DgCfGJ3Hv0WibEDpGEI3Xz0xjK6URzFW/bVJAg1Bi/ggZPg7tqs1s35EzMWwJqRhzY=
install:
- pip install --user awscli
- for i in $(cat .circle-ruby) ; do rvm install $i || exit 1 ; done
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle install || exit 1 ; done
script:
- curl -vI https://github.blog
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle exec rake || exit 1 ; done
deploy:
  provider: script
  script: aws s3 sync --delete _build/ s3://$BUCKET/ || travis_terminate 1
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: gGGeXle4Sd9J7oWoluIgj30pbPiK4AJsrh7HpzocE3FKeWpDJU8YiUdh/6qLia1rAoRcmBFA/N6A8hkYqmpbP2/+M7yoFfMfPK0aChyVS5pcqbBpLZM3TwF04yN82FnFzTB85IEjzm8qkDgLgpYyxqtBatd/ti/s4bm5QK1PatANKZ7Pk2zkH1Okoc2H9Zyg7vsm4pXSldkcSd6MrF6KgVq3oSCRW8m3Q0EKN4rnD0MLhKb1D1bu4nMntR0uyUtbX/+l85Xqrlk5zdbHtTwRl3RVIn5Y3QCFolF/CRiZ2Nhh1x9okKSLdLpxqkwccyoEo9lnyAt6C1bPM+VoIlK+rD4h3VZyvNRuH7WXcGPxWI3/uxlxoyS3A53gjUg/uhjf/NWmThPftsRKIPLzvzpV2niHOJzmRHlnya0H2hluwMiKmnDwp+kOxlMHn2vhKiQABGYrwkfb6ZKwshcsfTp9hmKH569GA7njNgRB59kKgZJLSJZJLVRhgEs7zEKIw/+vjSgtrZbZC3huryodT8YJJGfITtW+dZyBa47POVadXUdVFMVeSeclAQxmEp1JO+CxvuJ/OpcUJxep9XQxLNgCz0zemMKIWa5VAQXElU0CECWqyNSq0OcLxt9DDkqL7GLB9I7VRj9tTHPy17kJks8kTfBWJfij0XpKPpsbc9AO5t8=
