---
source: .
destination: _build

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- spec
- deps
- vendor
include:
- .well-known
highligher: nil
excerpt_separator: "<!--more-->"

gems:
- jekyll_prism

permalink: pretty

markdown: kramdown
markdown_ext: md
kramdown:
  input: GFM

timezone: US/Eastern
encoding: utf-8
...
