---
source: .
destination: _build
pygments: false
exclude:
    -   README.md
    -   LICENSE
encoding: UTF-8
future: false
excerpt_separator: "<!--more-->"
permalink: pretty
markdown:      redcarpet
markdown_ext:  md
social:
    github: akerl
    twitter: akerl
...

