---
source: .
destination: _build

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- spec
- vendor
include:
- .well-known
highligher: nil
excerpt_separator: "<!--more-->"

gems:
- jekyll_prism

assets:
  sources:
  - _assets
  - _deps
  js_compressor:  yui
  css_compressor: yui

permalink: pretty

markdown: kramdown
markdown_ext: md
kramdown:
  input: GFM

timezone: US/Eastern
encoding: utf-8

name: akerl's blogthing
description: Words about tech and stuff
url: http://akerl.org
...
