---
source: .
destination: _build
pygments: true
exclude:
    -   README.md
    -   LICENSE
encoding: UTF-8
future: false
excerpt_separator: <!--more-->
social:
    github: akerl
    twitter: akerl
...

