---
source: .
destination: _build

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - spec

highligher: nil
excerpt_separator: "<!--more-->"

permalink: pretty

markdown: kramdown
markdown_ext: md
kramdown:
  input: GFM

timezone: US/Eastern
...

