---
source: .
destination: _build

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- spec
- .asset-cache
- vendor
include:
- .well-known
highlighter: rouge
excerpt_separator: "<!--more-->"

assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
  - _assets

permalink: pretty

markdown: kramdown
markdown_ext: md
kramdown:
  input: GFM

timezone: US/Eastern
encoding: utf-8

name: akerl's blogthing
description: Words about tech and stuff
url: http://blog.akerl.org
...
