baseURL: https://blog.akerl.org
languageCode: en-us
title: akerl's blogthing

theme: anubis
paginate: 10
enableRobotsTXT: true

permalinks:
  post: /:year/:month/:day/:title

menu:
  footer:
  - identifier: sitesource
    name: Site Source
    title: Site Source
    url: https://github.com/akerl/blog
    weight: 0

params:
  author: Les Aker
  email: me@lesaker.org
  dateFormat: 2006-01-02
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false
  disableSummary: false
  rssAsSocialIcon: true
  social:
  - id: github
    name: akerl
  - id: instagram
    name: akerles
  - id: email
    name: me@lesaker.org
  goatCounter: goat.akerl.app

minify:
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true
